### ISSUE TITLE
Explicit search for emkey1/ish-AOK/issues/ can't locate THIS workflow

### ISSUE THREAD

**Issue by 62f** [emkey1/ish-AOK#25]
Yea I know it's HERE, but the GitHub contributor's search can't locate it by name.
<details>
ssl_client: www.nta-monitor.com: handshake failed: Connection reset by peer</details>

wget: error getting response: Invalid argument

__Originally posted by @62f in https://github.com/royhills/arp-scan/issues/59#issuecomment-845790060__

__Originally posted by @62f in https://github.com/emkey1/AOK/issues/4__
![image](https://user-images.githubusercontent.com/68332197/120413354-1b5a2c00-c326-11eb-85bf-f42464f229b4.jpeg)

**Comment by 62f** [comment]
In-app linked to site, working 😑solution.

**Comment by emkey1** [comment]
Hmm, looks to be working now..
<img width="599" alt="Screen Shot 2021-12-31 at 5 45 56 AM" src="https://user-images.githubusercontent.com/18100932/147826432-5524addf-c7ff-4bf4-a7ef-a95c57dc9031.png">
.
