### ISSUE TITLE
/ish you is or /ish you ain't there, baby?

### ISSUE THREAD

**Issue by 62f** [emkey1/ish-AOK#29]
Would it be possible to feed all the /ish files to Godzilla and still have them be around, too?

<details>

![image](https://user-images.githubusercontent.com/68332197/120824418-70649080-c526-11eb-9bf2-802737c78c7c.jpeg)
__Originally posted by @62f in https://github.com/emkey1/ish-AOK/issues/29__</details>

**Comment by emkey1** [comment]
Only Godzilla knows for sure and sadly I don't have his number.

The issue shown is odd.  I suspect reinstalling would solve the issue but have no idea why.  There seem to be some odd bugs with iSH, iOS and file access at times.

**Comment by 62f** [comment]
Yea iSH's 'filesystem inside a sandbox which can't grow faster than the app makes data inside it, goes catatonic.

**Comment by emkey1** [comment]
Doing some house cleaning.
