### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by 62f** [emkey1/ish-AOK#34]
![BFE151AC-70F3-4E3A-9E82-B698289F679F](https://user-images.githubusercontent.com/68332197/117942991-aae95d80-b2d9-11eb-96d0-f9dc408c7384.jpeg)
works on ish-AOK

__Originally posted by @62f in https://github.com/ish-app/ish/issues/273#issuecomment-839573141__

**Comment by Admin790811** [comment]
> ![BFE151AC-70F3-4E3A-9E82-B698289F679F](https://user-images.githubusercontent.com/68332197/117942991-aae95d80-b2d9-11eb-96d0-f9dc408c7384.jpeg)
> 
> works on ish-AOK
> 
> __Originally posted by @62f in https://github.com/ish-app/ish/issues/273#issuecomment-839573141__

**Comment by Admin790811** [comment]
> ![BFE151AC-70F3-4E3A-9E82-B698289F679F](https://user-images.githubusercontent.com/68332197/117942991-aae95d80-b2d9-11eb-96d0-f9dc408c7384.jpeg)
> 
> works on ish-AOK
> 
> __Originally posted by @62f in https://github.com/ish-app/ish/issues/273#issuecomment-839573141__

**Comment by emkey1** [comment]
Yes, htop and procps top commands work thanks to the inclusion of pending upstream PR #1066.  There are some limitations, but it's a nice addition.
