### ISSUE TITLE
442(apk) illegal instruction at 0xf7f8ec20: f4 8b 44 24 08 c7 44 24

### ISSUE THREAD

**Issue by 62f** [emkey1/ish-AOK#40]
```^C```
![image](https://user-images.githubusercontent.com/68332197/127965670-35f874ee-f153-4f7f-9ff3-1c5cf7a845af.jpeg) <details>442(apk) illegal instruction at 0xf7f8ec20: f4 8b 44 24 08 c7 44 24 </details>

**Comment by emkey1** [comment]
This appears to work fine in the current release? (1.2.4 Build 363)
